repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
      - id: mypy
        # exclude: ^docs/conf.py

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
    - id: isort
